config/routes.rb
Rails.application.routes.draw do
  root :to => 'welcome#index'
  resources 'politicians', only: [:index]
  resources :outings, only: [:index, :show]
  resources :users, only: [:new, :create, :edit, :update]
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'
  get '/dashboard' => 'users#show'
  get '/cart' => 'carts#index'
  post '/cart_increment' => 'carts#increment', :as => 'increment'
  post '/cart_decrement' => 'carts#decrement', :as => 'decrement'
  resources :orders, only: [:index, :show]
  post '/orders' => 'orders#create', :as => 'checkout'
  get '/:name' => 'politicians#show', :as => 'categories'
  resources :carts, only: [:create, :destroy]
  namespace :admin do
    resources :users, only: [:index]
    resources :outings, only: [:index, :edit, :update]
    post '/makes_admin' => 'users#make_admin', :as => 'makes_admin'
    get '/dashboard' => 'base#dashboard'
  end
  post '/order_cancel' => 'orders#cancel', :as => 'cancel'
  post '/order_paid' => 'orders#paid', :as => 'paid'
  post '/order_completed' => 'orders#completed', :as => 'completed'
end

app/views/shared/_outing.html.erb
<div class='col-md-4 outing-tile' id='outing-index'>
  <div class = 'col-md-6'>
    <img id='outing-image' src='<%= outing.image_url %>'><br>
  </div>
  <div class = 'col-md-6'>
    <h3 class = 'text-center'><%= link_to outing.title, outing_path(outing) %></h3>
    <p><strong><%= outing.adjusted_cost_currency %></strong></p>
    <p>with <%= link_to outing.politician.name, "/#{path_creator(outing.politician.name)}" %></p><br>
  </div>
  <div class = 'col-md-offset-2 col-md-8 outing-button'>
    <% if outing.retired? %>
    <p> Outing Retired </p>
    <% else %>
    <p><%= link_to "Add to Cart", carts_path(outing_id: outing.id),method: :POST, class:'btn btn-success btn-sm col-md-12' %></p>
    <% end %>
  </div>
</div>