config/routes.rb
Rails.application.routes.draw do
  root :to => 'welcome#index'
  resources 'politicians', only: [:index]
  resources :outings, only: [:index, :show]
  resources :users, only: [:new, :create, :edit, :update]
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'
  get '/dashboard' => 'users#show'
  get '/cart' => 'carts#index'
  post '/cart_increment' => 'carts#increment', :as => 'increment'
  post '/cart_decrement' => 'carts#decrement', :as => 'decrement'
  resources :orders, only: [:index, :show]
  post '/orders' => 'orders#create', :as => 'checkout'
  get '/:name' => 'politicians#show', :as => 'categories'
  resources :carts, only: [:create, :destroy]
  namespace :admin do
    resources :users, only: [:index]
    resources :outings, only: [:index, :edit, :update]
    post '/makes_admin' => 'users#make_admin', :as => 'makes_admin'
    get '/dashboard' => 'base#dashboard'
  end
  post '/order_cancel' => 'orders#cancel', :as => 'cancel'
  post '/order_paid' => 'orders#paid', :as => 'paid'
  post '/order_completed' => 'orders#completed', :as => 'completed'
end

app/models/cart.rb
class Cart
  include ActionView::Helpers::NumberHelper

  attr_reader :contents, :cart_content

  def initialize(initial_contents)
    @contents = initial_contents || {}
    @cart_content = {}
  end

  def add_outing(outing_id)
    @contents[outing_id.to_s] ||= 0
    @contents[outing_id.to_s] += 1
  end

  def sub_outing(outing_id)
    @contents[outing_id.to_s] -= 1
  end

  def contents_detailed
    contents.each do |outing_id, outing_qty|
      outing = Outing.find(outing_id)
      @cart_content[outing] = outing_qty
    end
    cart_content
  end

  def total
    contents_detailed.inject(0) do |cart_total, (outing, outing_qty)|
      cart_total += sub_total(outing, outing_qty)
      cart_total
    end
  end

  def sub_total(outing, quantity)
    outing.adjusted_cost * quantity
  end

  def sub_total_currency(outing, quantity)
    number_to_currency(sub_total(outing, quantity))
  end

  def total_currency
    number_to_currency(total)
  end

  def outings_count
    @contents.values.sum
  end

  def empty?
    return true if outings_count == 0
    false
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

  before_action :set_cart, only: [:create, :increment, :decrement]

  def index
    @cart = Cart.new(session[:cart])
  end

  def create
    @cart.add_outing(@outing.id)
    save_cart(@cart)
    redirect_to outings_path
  end

  def increment
    @cart.add_outing(@outing.id)
    save_cart(@cart)
    redirect_to cart_path
  end

  def decrement
    @cart.sub_outing(@outing.id)
    save_cart(@cart)
    redirect_to cart_path
  end

  def destroy
    outing = Outing.find(params[:id])
    session[:cart].delete(outing.id.to_s)
    link = "#{view_context.link_to(outing.title, outing_path(outing_id: outing.id))}"
    flash[:success] = "Successfully removed #{link} from your cart."
    redirect_to cart_path
  end

  private

  def set_cart
    @outing = Outing.find(params[:outing_id])
    @cart = Cart.new(session[:cart])
  end

  def save_cart(cart)
    session[:cart] = cart.contents
  end
end

app/views/carts/index.html.erb
<div class='container'>
  <div class = "col-md-4">
    <h1>Cart
      <% if !@cart.empty? && current_user %>
        <%= link_to "Checkout", checkout_path, method: :POST, class: "btn btn-primary" %>
      <% elsif !@cart.empty? %>
        <%= link_to "Login or Create Account to Checkout", checkout_path, method: :POST, class: "btn btn-primary" %>
      <% end %>
    </h1>
  </div>
  <div class = "col-md-8 text-right">
    <h1>Total Price: <%= @cart.total_currency %></h1>
  </div>

  <table class = "table">
    <tr>
      <th>Outing Title</th>
      <th>Description</th>
      <th>Image</th>
      <th>Price</th>
      <th>Quantity</th>
      <th>Sub Total</th>
      <th>Action</th>
    </tr>
    <% @cart.contents_detailed.each do |content, content_qty|%>
      <tr>
        <td><%= content.title %></td>
        <td><%= content.description %></td>
        <td><img src="<%= content.image_url %>" class="img-responsive" id="outing-photo"></td>
        <td><%= content.adjusted_cost_currency %></td>
        <td id='quantity'><%= link_to "+", increment_path(outing_id: content.id),method: :POST, class:'btn btn-success btn-xs', id: 'add' %>
          <%= content_qty %>
          <% if content_qty >= 2 %>
            <%= link_to "-", decrement_path(outing_id: content.id), method: :POST, class:'btn btn-warning btn-xs'%></td></td>
          <% end %>
          <td>
            <%= @cart.sub_total_currency(content, content_qty) %>
          </td>
        <td><%= link_to "Remove", "/carts/#{content.id}", method: :delete, class: "btn btn-danger btn-sm" %></td>
      </tr>
    <% end %>
    <tr>
    </tr>
  </table>
</div>