config/routes.rb
Rails.application.routes.draw do
  root :to => 'welcome#index'
  resources 'politicians', only: [:index]
  resources :outings, only: [:index, :show]
  resources :users, only: [:new, :create, :edit, :update]
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'
  get '/dashboard' => 'users#show'
  get '/cart' => 'carts#index'
  post '/cart_increment' => 'carts#increment', :as => 'increment'
  post '/cart_decrement' => 'carts#decrement', :as => 'decrement'
  resources :orders, only: [:index, :show]
  post '/orders' => 'orders#create', :as => 'checkout'
  get '/:name' => 'politicians#show', :as => 'categories'
  resources :carts, only: [:create, :destroy]
  namespace :admin do
    resources :users, only: [:index]
    resources :outings, only: [:index, :edit, :update]
    post '/makes_admin' => 'users#make_admin', :as => 'makes_admin'
    get '/dashboard' => 'base#dashboard'
  end
  post '/order_cancel' => 'orders#cancel', :as => 'cancel'
  post '/order_paid' => 'orders#paid', :as => 'paid'
  post '/order_completed' => 'orders#completed', :as => 'completed'
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController

  before_action :require_admin

  def require_admin
    render file: "/public/403" unless current_user && current_user.admin?
  end

  def dashboard
    @orders = Order.all
    @user = current_user
  end
end

app/views/admin/base/_admin-orders.html.erb
      <table class = "table">
        <tr>
          <th>Order ID</th>
          <th>Current Status</th>
          <th colspan="3" class = "text-center">Action</th>
        </tr>
        <% list.each do |order|%>
          <tr>
            <td><%= link_to order.id, order_path(order) %></td>
            <td><%= order.status %></td>
            <td>
              <% if order.ordered? || order.paid? %>
                <%= link_to "Cancel", cancel_path(id: order.id), method: "POST", class: "btn btn-default" %>
              <% end %>
              </td>
            <td>
              <% if order.ordered? %>
                <%= link_to "Mark as Paid", paid_path(id: order.id), method: "POST",  class: "btn btn-default" %>
              <% end %>
            </td>
            <td>
              <% if order.paid? %>
                <%= link_to "Mark as Completed", completed_path(id: order.id), method: "POST",  class: "btn btn-default" %>
              <% end %>
            </td>
          </tr>
        <% end %>
      </table>

app/views/admin/base/dashboard.html.erb
<div class='container'>
  <h1> Admin Dashboard </h1>
  <div>
    <div class="container">
      <div class="col-md-2"><p>Name: <%= @user.name %></p></div>
      <div class="col-md-2"><p>Email: <%= @user.email %></p></div>
      <div class="col-md-2"><%= link_to "Edit User", edit_user_path(@user), class: "btn btn-warning btn-lg" %></div>
    </div>

    <!-- Nav tabs -->
    <ul class="nav nav-tabs" role="tablist" id="admin-tabs">
      <li role="presentation" class="active"><a href="#all" aria-controls="all" role="tab" data-toggle="tab">All <span class="badge"><%= @orders.count %></a></li>
      <li role="presentation"><a href="#ordered" aria-controls="ordered" role="tab" data-toggle="tab">Ordered <span class="badge"><%= @orders.ordered.count %></a></li>
      <li role="presentation"><a href="#paid" aria-controls="paid" role="tab" data-toggle="tab">Paid <span class="badge"><%= @orders.paid.count %></a></li>
      <li role="presentation"><a href="#cancelled" aria-controls="cancelled" role="tab" data-toggle="tab">Cancelled <span class="badge"><%= @orders.cancelled.count %></a></li>
      <li role="presentation"><a href="#completed" aria-controls="completed" role="tab" data-toggle="tab">Completed <span class="badge"><%= @orders.completed.count %></a></li>
    </ul>

    <!-- Tab panes -->
    <div class="tab-content">
      <div role="tabpanel" class="tab-pane active" id="all">
          <%= render partial: "admin-orders", locals: {list: @orders} %>
      </div>
      <div role="tabpanel" class="tab-pane" id="ordered">
          <%= render partial: "admin-orders", locals: {list: @orders.ordered} %>
      </div>
      <div role="tabpanel" class="tab-pane" id="paid">
          <%= render partial: "admin-orders", locals: {list: @orders.paid} %>
      </div>
      <div role="tabpanel" class="tab-pane" id="cancelled">
          <%= render partial: "admin-orders", locals: {list: @orders.cancelled} %>
      </div>
      <div role="tabpanel" class="tab-pane" id="completed">
          <%= render partial: "admin-orders", locals: {list: @orders.completed} %>
      </div>
    </div>

  </div>
</div>