config/routes.rb
Rails.application.routes.draw do
  root :to => 'welcome#index'
  resources 'politicians', only: [:index]
  resources :outings, only: [:index, :show]
  resources :users, only: [:new, :create, :edit, :update]
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'
  get '/dashboard' => 'users#show'
  get '/cart' => 'carts#index'
  post '/cart_increment' => 'carts#increment', :as => 'increment'
  post '/cart_decrement' => 'carts#decrement', :as => 'decrement'
  resources :orders, only: [:index, :show]
  post '/orders' => 'orders#create', :as => 'checkout'
  get '/:name' => 'politicians#show', :as => 'categories'
  resources :carts, only: [:create, :destroy]
  namespace :admin do
    resources :users, only: [:index]
    resources :outings, only: [:index, :edit, :update]
    post '/makes_admin' => 'users#make_admin', :as => 'makes_admin'
    get '/dashboard' => 'base#dashboard'
  end
  post '/order_cancel' => 'orders#cancel', :as => 'cancel'
  post '/order_paid' => 'orders#paid', :as => 'paid'
  post '/order_completed' => 'orders#completed', :as => 'completed'
end

app/views/layouts/_flash.html.erb
<% flash.each do |name, msg| %>
  <div class="alert alert-<%= name %> alert-dismissable" role="alert">
    <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <span class="sr-only">Message: </span><%= sanitize(msg, tags: %w(a), attributes: %w(href rel data-method)) %>
  </div>
<% end %>

app/views/layouts/_header.html.erb
<header>

  <nav class="navbar navbar-light navbar-fixed-top navbar-pushin">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/"><img id="small_logo" src="<%= image_path('lobbify.png') %>"></a>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-left">
          <li><%= link_to "View Cart", cart_path, class: "btn btn-default btn-sm" %></li>
          <% if current_user && current_user.admin? %>
          <!-- Single button -->
          <li class="dropdown">
          <a href="#" class="dropdown-toggle btn btn-default btn-sm" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Admin <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "Outings Index", admin_outings_path, class: "btn btn-default btn-sm" %></li>
            <li><%= link_to "Admin Dashboard", admin_dashboard_path, class: "btn btn-default btn-sm" %></li>
            <li><%= link_to "Admin Users", admin_users_path, class: "btn btn-default btn-sm" %></li>
          </ul>
        </li>
          <% end %>
          <li class="label">Disclaimer: Lobbify is a parody website.</li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <% if current_user %>
            <li class = "label" >Logged in as <%= current_user.name %></li>
            <li><%= link_to "Logout", logout_path, method: :DELETE, class: "btn btn-default btn-sm" %></li>
            <li>
              <%= link_to "Orders", orders_path, class: "btn btn-default btn-sm" %>
            </li>
            <% if !current_user.admin? %>
            <li><%= link_to "Dashboard", dashboard_path, class: "btn btn-default btn-sm" %> </li>
            <% end %>
          <% else %>
            <li><%= link_to "Login", login_path, class: "btn btn-default btn-sm" %></li>
          <% end %>
          <li><%= link_to "Outings", outings_path, class: "btn btn-default btn-sm" %></li>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Lobbify</title>
    <%= csrf_meta_tags %>
    <link href="https://fonts.googleapis.com/css?family=Permanent+Marker|Quattrocento" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= render partial: "/layouts/header" %>
    <%= render partial: "/layouts/flash" %>
    <%= yield %>
    <footer>
      <p>Lobbify was developed using <a href="http://api.rubyonrails.org" target="_blank">Rails</a> by Daniel Rodriguez, Drew Palazzari, Laszlo Balogh, Nick Gheorghita</p>
      <p><a href="https://github.com/drod1000/lobbify" target="_blank">Source Code</a></p>
    </footer>
  </body>
</html>